### ISSUE TITLE
Spanish Translation Progress

### ISSUE THREAD

**Issue by horacioh** [gatsbyjs/gatsby-es#142]
## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. **Please take only one page at a time**.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, please read the [translation guide](https://www.gatsbyjs.org/contributing/gatsby-docs-translation-guide/#contributing-to-a-translation) to understand the Gatsby translation process.

Please be prompt with your translations! If you find that you can't commit anymore, let the maintainers know so they can assign the page to someone else.

## For Maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

- [ ] Home Page (@gatsbybot) #1

When PRs are merged, make sure to mark that page as completed!

## Core Pages

**These pages should be translated first.** These pages must be translated to be considered an official Gatsby localization.

### Community

* [x] community/code-of-conduct (@dantereve) #2 
    

### Tutorial

* [x] tutorial/index (@dantereve) #3 
* [ ] tutorial/part-zero (@alexislepresle)
* [ ] tutorial/part-one (@SamuelAlev)
* [ ] tutorial/part-two (@dantereve)
* [ ] tutorial/part-three
* [ ] tutorial/part-four
* [ ] tutorial/part-five
* [ ] tutorial/part-six
* [ ] tutorial/part-seven
* [ ] tutorial/part-eight
    

### Docs

* [ ] docs/index (@mindsers)
* [ ] docs/quick-start (@nclsppr) #4
* [ ] docs/recipes
* [ ] docs/glossary
* [ ] docs/gatsby-cli

**Comment by jorgeruvalcaba** [comment]
Can I take docs/recipes?

**Comment by erikbg7** [comment]
Hi! --> **docs/gatsby-cli**
